#ifndef GLM_DETAIL_TYPE_VEC1_H
#define GLM_DETAIL_TYPE_VEC1_H

#include "variadic_param.h"

#define GLM_VEC1_RSEQ() 1,0

#define GLM_VEC1_CONSTRUCTOR_PARAMS_0(A1)  
#define GLM_VEC1_CONSTRUCTOR_PARAMS_1(A1) GLM_VARIADIC_PARAM(A1)
#define GLM_VEC1_CONSTRUCTOR_PARAMS_(A1, N, ...) N, GLM_VEC1_CONSTRUCTOR_PARAMS_ ## N (A1)
#define GLM_VEC1_CONSTRUCTOR_PARAMS(...) GLM_VEC1_CONSTRUCTOR_PARAMS_(__VA_ARGS__)

#define GLM_VEC1_CONSTRUCTOR(T, Q, ...) GLM_VECTOR_CONSTRUCTOR_NAME(1, T, Q)(GLM_VEC1_CONSTRUCTOR_PARAMS(__VA_ARGS__, , GLM_VEC1_RSEQ()))
#define glm_tvec1(T, Q, ...) GLM_VEC1_CONSTRUCTOR(T, Q, __VA_ARGS__)

#endif /* GLM_DETAIL_TYPE_VEC1_H */