#ifndef GLM_DETAIL_TYPE_VEC1_H
#define GLM_DETAIL_TYPE_VEC1_H

#include "type_vec.h"

#define GLM_VEC1_CONSTRUCTOR_PARAMS_0(_A1)  
#define GLM_VEC1_CONSTRUCTOR_PARAMS_1(_A1) GLM_VARIADIC_PARAM(_A1)
#define GLM_VEC1_CONSTRUCTOR_PARAMS_(_A1, _N, ...) _N, GLM_VEC1_CONSTRUCTOR_PARAMS_ ## _N (_A1)
#define GLM_VEC1_CONSTRUCTOR_RSEQ() 1, 0
#define GLM_VEC1_CONSTRUCTOR_PARAMS(...) GLM_VEC1_CONSTRUCTOR_PARAMS_(__VA_ARGS__, 1, 0)

#define GLM_VEC1_CONSTRUCTOR(T, Q, ...) GLM_VEC_CONSTRUCTOR_ADDR(1, T, Q)( GLM_VEC2_CONSTRUCTOR_PARAMS(__VA_ARGS__) )

#define glm_tvec1(T, Q, ...) GLM_VEC1_CONSTRUCTOR(T, Q, __VA_ARGS__)

#endif /* GLM_DETAIL_TYPE_VEC1_H */