#ifndef GLM_DETAIL_TYPE_VEC2_H
#define GLM_DETAIL_TYPE_VEC2_H

#include "variadic_param.h"

#define GLM_VEC2_RSEQ() 2,1,0

#define GLM_VEC2_CTOR_PARAMS_0(A1, A2)  
#define GLM_VEC2_CTOR_PARAMS_1(A1, A2) GLM_VARIADIC_PARAM(A1)
#define GLM_VEC2_CTOR_PARAMS_2(A1, A2) GLM_VARIADIC_PARAM(A1), GLM_VARIADIC_PARAM(A2)
#define GLM_VEC2_CTOR_PARAMS_(A1, A2, N, ...) N, GLM_VEC2_CTOR_PARAMS_ ## N (A1, A2)
#define GLM_VEC2_CTOR_PARAMS(...) GLM_VEC2_CTOR_PARAMS_(__VA_ARGS__)

#define GLM_VEC2_CTOR(T, Q, ...) GLM_VEC_CTOR_NAME(2, T, Q)(GLM_VEC2_CTOR_PARAMS(__VA_ARGS__, GLM_VEC2_RSEQ()))
#define glm_tvec2(T, Q, ...) GLM_VEC2_CTOR(T, Q, __VA_ARGS__)

#endif /* GLM_DETAIL_TYPE_VEC2_H */