#ifndef GLM_DETAIL_TYPE_VEC4_H
#define GLM_DETAIL_TYPE_VEC4_H

#include "type_vec.h"

#define GLM_VEC4_CONSTRUCTOR_PARAMS_0(_A1, _A2, _A3, _A4)  
#define GLM_VEC4_CONSTRUCTOR_PARAMS_1(_A1, _A2, _A3, _A4) GLM_VARIADIC_PARAM(_A1) 
#define GLM_VEC4_CONSTRUCTOR_PARAMS_2(_A1, _A2, _A3, _A4) GLM_VARIADIC_PARAM(_A1), GLM_VARIADIC_PARAM(_A2)
#define GLM_VEC4_CONSTRUCTOR_PARAMS_3(_A1, _A2, _A3, _A4) GLM_VARIADIC_PARAM(_A1), GLM_VARIADIC_PARAM(_A2), GLM_VARIADIC_PARAM(_A3)
#define GLM_VEC4_CONSTRUCTOR_PARAMS_4(_A1, _A2, _A3, _A4) GLM_VARIADIC_PARAM(_A1), GLM_VARIADIC_PARAM(_A2), GLM_VARIADIC_PARAM(_A3), GLM_VARIADIC_PARAM(_A4)
#define GLM_VEC4_CONSTRUCTOR_PARAMS_(_A1, _A2, _A3, _A4, _N, ...) _N, GLM_VEC4_CONSTRUCTOR_PARAMS_ ## _N (_A1, _A2, _A3, _A4)
#define GLM_VEC4_CONSTRUCTOR_RSEQ() 4, 3, 2, 1, 0
#define GLM_VEC4_CONSTRUCTOR_PARAMS(...) GLM_VEC4_CONSTRUCTOR_PARAMS_(__VA_ARGS__, 4, 3, 2, 1, 0)

#define GLM_VEC4_CONSTRUCTOR(T, Q, ...) GLM_VEC_CONSTRUCTOR_ADDR(4, T, Q)( GLM_VEC4_CONSTRUCTOR_PARAMS(__VA_ARGS__) )

#define glm_tvec4(T, Q, ...) GLM_VEC4_CONSTRUCTOR(T, Q, __VA_ARGS__)

#endif /* GLM_DETAIL_TYPE_VEC4_H */