#ifndef GLM_SWIZZLE_H
#define GLM_SWIZZLE_H

#include <glm/vec2.h>
#include <glm/vec3.h>
#include <glm/vec4.h>

#define GLM_SWIZZLE_XYZW 0x00000001
#define GLM_SWIZZLE_RGBA 0x00000002
#define GLM_SWIZZLE_STQP 0x00000004
#define GLM_SWIZZLE_ALL (GLM_SWIZZLE_XYZW | GLM_SWIZZLE_RGBA | GLM_SWIZZLE_STQP)

#if(GLM_SWIZZLE & GLM_SWIZZLE_XYZW)

#define   x(_) swizzle(_, 0)
#define   y(_) swizzle(_, 1)
#define   z(_) swizzle(_, 2)
#define   w(_) swizzle(_, 3)
#define  xx(_) swizzle(_, 0, 0)
#define  xy(_) swizzle(_, 0, 1)
#define  xz(_) swizzle(_, 0, 2)
#define  xw(_) swizzle(_, 0, 3)
#define  yx(_) swizzle(_, 1, 0)
#define  yy(_) swizzle(_, 1, 1)
#define  yz(_) swizzle(_, 1, 2)
#define  yw(_) swizzle(_, 1, 3)
#define  zx(_) swizzle(_, 2, 0)
#define  zy(_) swizzle(_, 2, 1)
#define  zz(_) swizzle(_, 2, 2)
#define  zw(_) swizzle(_, 2, 3)
#define  wx(_) swizzle(_, 3, 0)
#define  wy(_) swizzle(_, 3, 1)
#define  wz(_) swizzle(_, 3, 2)
#define  ww(_) swizzle(_, 3, 3)
#define xxx(_) swizzle(_, 0, 0, 0)
#define xxy(_) swizzle(_, 0, 0, 1)
#define xxz(_) swizzle(_, 0, 0, 2)
#define xxw(_) swizzle(_, 0, 0, 3)
#define xyx(_) swizzle(_, 0, 1, 0)
#define xyy(_) swizzle(_, 0, 1, 1)
#define xyz(_) swizzle(_, 0, 1, 2)
#define xyw(_) swizzle(_, 0, 1, 3)
#define xzx(_) swizzle(_, 0, 2, 0)
#define xzy(_) swizzle(_, 0, 2, 1)
#define xzz(_) swizzle(_, 0, 2, 2)
#define xzw(_) swizzle(_, 0, 2, 3)
#define xwx(_) swizzle(_, 0, 3, 0)
#define xwy(_) swizzle(_, 0, 3, 1)
#define xwz(_) swizzle(_, 0, 3, 2)
#define xww(_) swizzle(_, 0, 3, 3)
#define yxx(_) swizzle(_, 1, 0, 0)
#define yxy(_) swizzle(_, 1, 0, 1)
#define yxz(_) swizzle(_, 1, 0, 2)
#define yxw(_) swizzle(_, 1, 0, 3)
#define yyx(_) swizzle(_, 1, 1, 0)
#define yyy(_) swizzle(_, 1, 1, 1)
#define yyz(_) swizzle(_, 1, 1, 2)
#define yyw(_) swizzle(_, 1, 1, 3)
#define yzx(_) swizzle(_, 1, 2, 0)
#define yzy(_) swizzle(_, 1, 2, 1)
#define yzz(_) swizzle(_, 1, 2, 2)
#define yzw(_) swizzle(_, 1, 2, 3)
#define ywx(_) swizzle(_, 1, 3, 0)
#define ywy(_) swizzle(_, 1, 3, 1)
#define ywz(_) swizzle(_, 1, 3, 2)
#define yww(_) swizzle(_, 1, 3, 3)
#define zxx(_) swizzle(_, 2, 0, 0)
#define zxy(_) swizzle(_, 2, 0, 1)
#define zxz(_) swizzle(_, 2, 0, 2)
#define zxw(_) swizzle(_, 2, 0, 3)
#define zyx(_) swizzle(_, 2, 1, 0)
#define zyy(_) swizzle(_, 2, 1, 1)
#define zyz(_) swizzle(_, 2, 1, 2)
#define zyw(_) swizzle(_, 2, 1, 3)
#define zzx(_) swizzle(_, 2, 2, 0)
#define zzy(_) swizzle(_, 2, 2, 1)
#define zzz(_) swizzle(_, 2, 2, 2)
#define zzw(_) swizzle(_, 2, 2, 3)
#define zwx(_) swizzle(_, 2, 3, 0)
#define zwy(_) swizzle(_, 2, 3, 1)
#define zwz(_) swizzle(_, 2, 3, 2)
#define zww(_) swizzle(_, 2, 3, 3)
#define wxx(_) swizzle(_, 2, 0, 0)
#define wxy(_) swizzle(_, 3, 0, 1)
#define wxz(_) swizzle(_, 3, 0, 2)
#define wxw(_) swizzle(_, 3, 0, 3)
#define wyx(_) swizzle(_, 3, 1, 0)
#define wyy(_) swizzle(_, 3, 1, 1)
#define wyz(_) swizzle(_, 3, 1, 2)
#define wyw(_) swizzle(_, 3, 1, 3)
#define wzx(_) swizzle(_, 3, 2, 0)
#define wzy(_) swizzle(_, 3, 2, 1)
#define wzz(_) swizzle(_, 3, 2, 2)
#define wzw(_) swizzle(_, 3, 2, 3)
#define wwx(_) swizzle(_, 3, 3, 0)
#define wwy(_) swizzle(_, 3, 3, 1)
#define wwz(_) swizzle(_, 3, 3, 3)
#define www(_) swizzle(_, 3, 3, 3)

#endif

#endif /* GLM_SWIZZLE_H */
